Schemas ver1
Pan-Canadian-Genome-Library/data-dictionary pull request #1
Opened 2024-03-20 13:58 UTC by edsu7

2024-03-21 17:08 UTC, lindaxiang requested changes

2024-03-21 17:08 UTC, lindaxiang commented on schemas/participant.json
> +    "description": "The collection of data elements related to a specific donor in an ARGO program.",
ARGO --> PCGL

2024-03-21 17:08 UTC, lindaxiang commented on schemas/sample.json
> +  "description": "The collection of data elements required to register the required Donor-Specimen-Sample data to the ARGO Data Platform. Registration of samples is required before molecular and clin
ARGO --> PCGL

2024-03-21 18:49 UTC, guanqiaofeng commented on schemas/participant.json
> +    "description": "The collection of data elements related to a specific donor in a PCGL program.",
addressing:
https://github.com/Pan-Canadian-Genome-Library/data-dictionary/pull/1#discussion_r1534306519

2024-03-21 18:54 UTC, guanqiaofeng commented on schemas/sample.json
> +  "description": "The collection of data elements required to register the required Donor-Specimen-Sample data to the PCGL Data Platform. Registration of samples is required before molecular and clin
addressing https://github.com/Pan-Canadian-Genome-Library/data-dictionary/pull/1#discussion_r1534308416

2024-03-22 18:44 UTC, lindaxiang approved these changes

2024-03-22 20:49 UTC, leoraba requested changes

2024-03-27 14:44 UTC, joneubank commented on schemas/participant.json
> +                "core": true,
Do we have a definition and meaning for what "core" field means? This feels like a carry over from ARGO that doesn't have a PCGL equivalent.

2024-03-27 14:48 UTC, joneubank commented on schemas/participant.json
> +                "notes": "Source: MOH; All4One : Month,year of birth; mCODE STU3: Patient.birthDate; Phenopacket: Individual.date_of_birth; Beacon V2: Individual.date_of_birth"
We put `Source` in all our notes... would we want to just add a `source` property to our meta?

Similarly, would we want a separate property to list the field from other data sets that maps here?
ex. `"mapping": "All4One:Month,year of birth|mCODE STU3: Patient.birthDate|Phenopacket:Individual.date_of_birth"` etc.

2024-03-27 14:55 UTC, joneubank commented on references/regex.json
> +    "submitter_id": "^[A-Za-z0-9\\-\\._]{1,64}$",
Do we really need to restrict submitters to a max length 64 restriction? I think our only rule is the need for min length of 1, not sure we care about max length at all.

```suggestion
    "submitter_id": "^[A-Za-z0-9\\-\\._]+$",
```

2024-04-02 17:50 UTC, edsu7 commented on references/regex.json
> +    "submitter_id": "^[A-Za-z0-9\\-\\._]+$",
As per jon's suggestion:
https://github.com/Pan-Canadian-Genome-Library/data-dictionary/pull/1#discussion_r1541284510

2024-04-02 17:51 UTC, edsu7 commented on references/regex.json
> +    "yyyy_mm": "^\\d{4}-(0[1-9]|1[012])$",
As per Jon's suggestion:
https://github.com/Pan-Canadian-Genome-Library/data-dictionary/pull/1#discussion_r1541278221

2024-04-02 17:51 UTC, edsu7 commented on schemas/participant.json
> +          "source": "MOH/ARGO",
As per jon's suggestion:
https://github.com/Pan-Canadian-Genome-Library/data-dictionary/pull/1#discussion_r1541271035

Source and mappings were added to meta

2024-04-02 17:52 UTC, edsu7 commented on schemas/participant.json
> +        "name": "sex_at_birth",
`core` has been removed as per:
https://github.com/Pan-Canadian-Genome-Library/data-dictionary/pull/1#discussion_r1541264488

2024-04-02 17:53 UTC, edsu7 commented on schemas/participant.json
> +          "notes": "EDI indicator",
@lindaxiang do we want EDI indicator as its own field?

2024-04-02 18:36 UTC, leoraba requested changes
change default export as an array

2024-04-02 18:36 UTC, leoraba commented on schemas/index.js
> +export default { study, participant, sample, specimen };
```suggestion
export default [study, participant, sample, specimen];
```

2024-04-02 21:15 UTC, edsu7 commented
Dictionary in lectern:
https://lectern.overture-sandbox.cumulus.genomeinformatics.org/dictionaries/660c583ec7e3a638393ac462

2024-04-03 14:03 UTC, lindaxiang approved these changes

2024-04-03 14:03 UTC, lindaxiang commented on schemas/participant.json
> +        "description": "Refers to an individual's personal and social identity as a man, woman or non-binary person (a person who is not exclusively a man or a woman). The provided values are based o
little typo: categoried --> categories

2024-04-04 13:54 UTC, merged